### ISSUE TITLE
Should this still be favored over key-chord?

### ISSUE THREAD

**Issue by tarsius** [vlevit/key-seq.el#3]
Your library commentary contains this:

> The code in key-seq.el is 99% copy/paste from key-chord.el.

While I did not see an explicit mention of this feature in `key-chord`'s documentation, this seems to imply that it supports that too now:

> Don't chord key combinations that exists in the languages you typically write. [...] And don't forget to check both permutations: "fg" and "gf".

**Comment by vlevit** [comment]
> don't forget to check both permutations: "fg" and "gf".

I read it as if you define "fg" don't forget to checkout that "gf" is not used in your typing. Because these bindings will be treated equally by `key-chord`. In contrast `key-seq` will threat them differently.

Does it make sense for you or did I miss your point?

**Comment by vlevit** [comment]
Just to clarify. `key-seq` is not a copy of `key-chord`, actually `key-seq` depends on `key-chord`. It redefines single function of `key-chord` and adds similar commands for bindings. Hence `key-seq` contains almost no unique code, though it doesn't duplicate functionality of `key-chord`. It's possible to use `key-chord` and `key-seq` simultaneously. Two packages have a bit different ideas: `key-chord` is about keybindings composed of keys pressed (almost) simultaneously (so the order doesn't matter), while `key-seq` is about keys pressed in the specific order with a small delay.  

I'm closing it now. Feel free to re-open if you think it is still relevant.
